"""Generate inspire_profile.txt from INSPIRE papers.

This generates the auto-derived profile (inspire_profile.txt), which is
separate from the hand-curated profile (interest_profile.txt). The scorer
reads both files. Monthly INSPIRE regeneration only touches this file,
so hand-curated priorities are never overwritten.

Usage:
    python3 -m tools.setup_inspire K.Y.Oda.1
    python3 -m tools.setup_inspire K.Y.Oda.1 --name "Kin-ya Oda" --affiliation "TWCU"
    python3 -m tools.setup_inspire N.Ogawa.4 --profile ogawa
    python3 -m tools.setup_inspire --search "Kin-ya Oda"
"""

import argparse
import sys
from collections import Counter
from pathlib import Path

import yaml

from .fetch_inspire import fetch_papers, lookup_author, search_authors

ROOT_DIR = Path(__file__).resolve().parent.parent
PROFILES_DIR = ROOT_DIR / "profiles"
DEFAULT_PROFILE = "default"


def extract_categories(papers, min_fraction=0.05):
    """Extract arXiv categories appearing in >= min_fraction of papers.

    Returns sorted list of category strings (primary + secondary tiers).
    """
    if not papers:
        return []
    total = len(papers)
    counts = Counter()
    for p in papers:
        for c in p.get("categories", []):
            counts[c] += 1
    return sorted(cat for cat, n in counts.items() if n / total >= min_fraction)




def update_profile_config(profile_name, bai, inspire_categories, name=None, affiliation=None):
    """Update profile config.yaml with inspire_bai and inspire_arxiv_categories.

    Moves from arxiv_categories to inspire_arxiv_categories any entries now
    covered by INSPIRE. Prints a notification when this happens.

    name and affiliation are stored as inspire_name / inspire_affiliation so
    monthly auto-updates can regenerate inspire_profile.txt with the correct
    display name without user intervention.

    Note: user-added comments in config.yaml are not preserved on rewrite.
    """
    config_path = PROFILES_DIR / profile_name / "config.yaml"

    if config_path.exists():
        with open(config_path, encoding="utf-8") as f:
            config = yaml.safe_load(f) or {}
    else:
        config = {}

    # Remove auto-generated fields before processing manual entries
    config.pop("inspire_bai", None)
    config.pop("inspire_arxiv_categories", None)
    # Preserve existing name/affiliation if not provided
    if name is None:
        name = config.pop("inspire_name", None)
    else:
        config.pop("inspire_name", None)
    if affiliation is None:
        affiliation = config.pop("inspire_affiliation", None)
    else:
        config.pop("inspire_affiliation", None)

    # Remove from manual arxiv_categories anything now covered by inspire list
    manual = config.pop("arxiv_categories", None) or []
    inspire_set = set(inspire_categories)
    moved = [c for c in manual if c in inspire_set]
    remaining = [c for c in manual if c not in inspire_set]
    if moved:
        print(f"  Note: moved {moved} from manual arxiv_categories to inspire_arxiv_categories")

    # Build output dict in canonical key order (Python 3.7+ preserves insertion order).
    # yaml.dump handles all serialization — no manual field management needed.
    # Canonical order: auto-generated first, known fields next, unknown extras, manual last.
    KNOWN_ORDER = ["language", "scoring_threshold", "channels", "style",
                   "scoring_instructions"]
    output = {}
    output["inspire_bai"] = bai
    if name:
        output["inspire_name"] = name
    if affiliation:
        output["inspire_affiliation"] = affiliation
    output["inspire_arxiv_categories"] = inspire_categories
    for k in KNOWN_ORDER:
        if k in config:
            output[k] = config.pop(k)
    output.update(config)  # any remaining unknown fields
    if remaining:
        output["arxiv_categories"] = remaining

    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(f"# profiles/{profile_name}/config.yaml\n")
        f.write("# inspire_bai and inspire_arxiv_categories: auto-generated by setup_inspire.\n")
        f.write("# Edit arxiv_categories to add manual extras.\n\n")
        f.write(yaml.dump(output, default_flow_style=False, allow_unicode=True,
                          sort_keys=False))


def build_profile(papers, author_bai, name=None, affiliation=None):
    """Generate a research interest profile from paper list."""
    # Extract the author's last name from BAI (e.g. "K.Y.Oda.1" -> "Oda")
    bai_parts = author_bai.split(".")
    author_surname = bai_parts[-2] if len(bai_parts) >= 2 else bai_parts[0]

    all_categories = Counter()
    all_coauthors = Counter()
    recent_titles = []

    for p in papers:
        for c in p.get("categories", []):
            all_categories[c] += 1

        for a in p.get("authors", []):
            if author_surname not in a:
                all_coauthors[a] += 1

        if p.get("year", 0) >= 2020:
            recent_titles.append(p.get("title", ""))

    # Classify categories into tiers by publication weight
    total_papers = len(papers)
    primary_cats = []    # >=20% of papers
    secondary_cats = []  # >=5% of papers
    peripheral_cats = [] # <5% of papers (typically from cross-listing)
    for cat, count in all_categories.most_common():
        frac = count / total_papers
        entry = f"{cat} ({count}, {frac:.0%})"
        if frac >= 0.20:
            primary_cats.append(entry)
        elif frac >= 0.05:
            secondary_cats.append(entry)
        else:
            peripheral_cats.append(entry)

    top_collabs = [n for n, _ in all_coauthors.most_common(15)]

    display_name = name or author_bai
    affil_line = f"\nAffiliation: {affiliation}" if affiliation else ""

    # Build category weight section
    cat_lines = []
    if primary_cats:
        cat_lines.append(f"Primary fields (>=20%): {', '.join(primary_cats)}")
    if secondary_cats:
        cat_lines.append(f"Secondary fields (5-20%): {', '.join(secondary_cats)}")
    if peripheral_cats:
        cat_lines.append(f"Peripheral fields (<5%, via cross-listing): {', '.join(peripheral_cats)}")
    cat_section = "\n".join(cat_lines)

    profile = f"""Research Interest Profile: {display_name}
{affil_line}

Publication record: {len(papers)} papers (including cross-listed)

{cat_section}

Frequent collaborators: {', '.join(top_collabs)}

Recent focus (2020-present): {'; '.join(recent_titles[:10])}

When scoring papers, consider:
1. Direct overlap with primary/secondary fields (highest relevance)
2. Papers by frequent collaborators (high relevance)
3. New methods or results applicable to the above themes (moderate relevance)
4. Peripheral fields: relevant only if connecting to primary interests (lower relevance)
"""
    return profile


def regenerate_profile(bai, profile_name, name=None, affiliation=None):
    """Fetch from INSPIRE and write inspire_profile.txt + update config.yaml categories.

    Returns True if updated.
    """
    papers = fetch_papers(bai)
    if not papers:
        return False

    profile = build_profile(papers, bai, name, affiliation)

    output_dir = PROFILES_DIR / profile_name
    output_dir.mkdir(parents=True, exist_ok=True)

    output_path = output_dir / "inspire_profile.txt"
    output_path.write_text(profile, encoding="utf-8")

    # Update config.yaml with inspire_bai, name, affiliation, and auto-generated categories
    inspire_categories = extract_categories(papers)
    update_profile_config(profile_name, bai, inspire_categories, name, affiliation)

    return True


def resolve_bai(query):
    """Search INSPIRE for an author name and let the user pick.

    Returns (bai, name, affiliation) or exits if no match.
    """
    print(f"Searching INSPIRE for \"{query}\"...")
    candidates = search_authors(query)
    if not candidates:
        print("No authors found. Try a different spelling.")
        sys.exit(1)

    print(f"\n  Found {len(candidates)} candidate(s):\n")
    for i, c in enumerate(candidates, 1):
        affil = f" ({c['affiliation']})" if c["affiliation"] else ""
        print(f"  [{i}] {c['name']}{affil}  —  BAI: {c['bai']}")

    if len(candidates) == 1:
        chosen = candidates[0]
        print(f"\n  → Using {chosen['bai']}")
    else:
        while True:
            try:
                choice = input("\n  Select number (0 to cancel): ").strip()
                idx = int(choice)
            except (ValueError, EOFError):
                continue
            if idx == 0:
                print("Cancelled.")
                sys.exit(0)
            if 1 <= idx <= len(candidates):
                chosen = candidates[idx - 1]
                break
            print(f"  Enter 1-{len(candidates)} or 0 to cancel.")

    return chosen["bai"], chosen["name"], chosen["affiliation"]


def main():
    parser = argparse.ArgumentParser(description="Generate interest profile from INSPIRE")
    parser.add_argument("bai", nargs="?", help="INSPIRE BAI (e.g. K.Y.Oda.1)")
    parser.add_argument("--search", "-s", help="Search by author name instead of BAI")
    parser.add_argument("--name", help="Display name")
    parser.add_argument("--affiliation", help="Affiliation")
    parser.add_argument("--profile", default=DEFAULT_PROFILE,
                        help="Profile name (writes to profiles/<name>/, default: %(default)s)")
    args = parser.parse_args()

    if args.search:
        bai, resolved_name, resolved_affil = resolve_bai(args.search)
        name = args.name or resolved_name
        affiliation = args.affiliation or resolved_affil
    elif args.bai:
        bai = args.bai
        name = args.name
        affiliation = args.affiliation
        # Skip author confirmation if this BAI is already verified in the profile config.
        profile_config_path = PROFILES_DIR / args.profile / "config.yaml"
        already_verified = False
        if profile_config_path.exists():
            existing = yaml.safe_load(profile_config_path.read_text(encoding="utf-8")) or {}
            if existing.get("inspire_bai") == bai:
                already_verified = True
                if not name:
                    name = existing.get("inspire_name")
                if not affiliation:
                    affiliation = existing.get("inspire_affiliation")

        if not already_verified:
            # First-time setup or BAI changed: confirm the BAI resolves to the right person.
            try:
                author = lookup_author(bai)
            except Exception as e:
                print(f"  Warning: Could not reach INSPIRE ({type(e).__name__}). Skipping author check.")
                author = None
            if author:
                affil_str = f" ({author['affiliation']})" if author["affiliation"] else ""
                print(f"  INSPIRE: {author['name']}{affil_str}  —  BAI: {bai}")
                try:
                    answer = input("  Continue? [Y/n] ").strip().lower()
                except EOFError:
                    answer = "y"
                if answer not in ("", "y", "yes"):
                    print("Aborted.")
                    sys.exit(0)
                if not name:
                    name = author["name"]
                if not affiliation:
                    affiliation = author["affiliation"]
            else:
                print(f"  Warning: BAI {bai} not found in INSPIRE authors index.")
                try:
                    answer = input("  Proceed anyway? [y/N] ").strip().lower()
                except EOFError:
                    answer = "n"
                if answer not in ("y", "yes"):
                    print("Aborted.")
                    sys.exit(0)
    else:
        parser.error("Provide a BAI or use --search to find one by name")

    print(f"Fetching papers for {bai} from INSPIRE...")
    if regenerate_profile(bai, args.profile, name, affiliation):
        output_path = PROFILES_DIR / args.profile / "inspire_profile.txt"
        print(f"  Wrote INSPIRE profile to {output_path}")

        interest_path = PROFILES_DIR / args.profile / "interest_profile.txt"
        if not interest_path.exists():
            print(f"\n  Note: {interest_path} does not exist yet.")
            print("  Create it from templates/interest_profile.txt to add your personal priorities.")
        else:
            print(f"\n  Hand-curated profile at {interest_path} is untouched.")

        print(f"\nGenerated INSPIRE profile:\n{output_path.read_text(encoding='utf-8')}")
    else:
        print("No papers found. Check the BAI.")
        sys.exit(1)


if __name__ == "__main__":
    main()
